### PR TITLE
feat: support uncompressing symlink

### PR DESCRIPTION
**Pull request by atian25**
closes https://github.com/node-modules/compressing/pull/58 https://github.com/node-modules/compressing/issues/93

### CODE REVIEW

**Comment by fengmk2** [comment]
@atian25 ci 没过。

**Comment by fengmk2** [comment]
@atian25 ci 修一下？

**Comment by atian25** [comment]
ci 文件权限那个有点奇怪，本地没问题，ci 的权限不一样

**Comment by fengmk2** [comment]
我晚点 rebase 一下继续推进。

**Comment by ayushmanchhabra** [comment]
@fengmk2 @atian25 I am interested in getting this merged. The module is used in [nw-builder](https://github.com/nwutils/nw-builder). Currently, it is not recognising symbolic links on decompression. This would help a ton!

**Comment by fengmk2** [comment]
@ayushmanchhabra Sure, I will merge it in this week.

**Comment by zkrige** [comment]
While this looks like it should work, its still not processing symlinks properly on extract

**Pull request merged**
