### PR TITLE
fix: Use '/' path separator on Windows for tar archives

### PR DESCRIPTION
**Pull request by Infiltrator**
Creating a tar archive on Windows with a directory results instead in the file having '\\' in its name, and on extraction on POSIX, does not create the appropriate directory.

To fix this, use `path.posix` to force the '/' path separator even if creating the archive on Windows.

closes https://github.com/node-modules/compressing/issues/22

### CODE REVIEW

**Comment by Infiltrator** [comment]
Fixes #22 .

**Comment by Infiltrator** [comment]
Hmmm.  How do I squash commits in the browser?

**Comment by zevero** [comment]
Will this be merged?
Currently tgz created on windows are not readable on linux.

**Comment by fengmk2** [comment]
@Infiltrator Can you add a test case for this bug fix?

**Comment by DesignByOnyx** [comment]
I know this issue is old, but I confirmed that this fixes issues on Windows 10. I am generating a tgz using:

```js
compressing.tgz.compressDir(stagingDir, outputDest);
```

Tools like 7Zip are unable to correctly extract the folder structure. When I apply the changes in this PR, everything works as expected.

**Review by fengmk2 — APPROVED** [review]

**Comment by DesignByOnyx** [comment]
Thanks @fengmk2 for pushing this along. I'm trying to create a test for this, but there are a couple issues which fall into the "not worth it" category for me:

- The tests will need to run on Windows to make sure it _truly_ passes. 
- The bug doesn't happen using this library alone - meaning, this tool can uncompress files that it created. In order to actually test this, we will need to run `tar` commands (if it exists) or 3rd party tools to uncompress the files.

None of this seems worth it for what appears to be a reasonable and simple fix. Thanks for getting this in!

**Pull request merged**
